Improve todo OpenAPI spec
stoplightio/studio-demo pull request #11
Opened 2021-04-06 01:24 UTC by mnaumanali94

2021-04-06 21:51 UTC, marbemac requested changes

2021-04-06 21:51 UTC, marbemac commented on reference/todos/todo.v1.yaml
> +  - API Key: []
Should add security to the operations that require it (all the mutations), rather than globally.

2021-04-06 21:51 UTC, marbemac commented on reference/todos/todo.v1.yaml
> +        '':
attn

2021-04-06 21:51 UTC, marbemac commented on reference/todos/todo.v1.yaml
> +  termsOfService: 'https://docs.github.com/articles/github-terms-of-service'
what's this?

2021-04-06 21:51 UTC, marbemac commented on reference/todos/todo.v1.yaml
> +    url: 'https://www.stoplight.io'
drop the www

2021-04-06 21:51 UTC, marbemac commented on reference/todos/todo.v1.yaml
> +  description: "![](https://i.ibb.co/v3Yt03v/todo-api-background.png)\n\n## \U0001F4AB Overview\n\nTo Do API provides a simple way for people to manage their tasks and plan their day. This API can be
> CORS support is necessary to send test requests to the API from docs in the browser

> The implementation lives in this [GitHub repo](https://github.com/marbemac/stoplight-todos)

I don't think we should point folks over there - perhaps could just point to the openapi file in the studio-demo repository?

2021-04-14 01:37 UTC, mnaumanali94 commented on reference/todos/todo.v1.yaml
> +  termsOfService: 'https://docs.github.com/articles/github-terms-of-service'
Updated to point to our terms of service. They show up pretty nicely in elements so like it.

2021-04-14 01:38 UTC, mnaumanali94 commented on reference/todos/todo.v1.yaml
> +  - API Key: []
Added empty security for the operations that don't require it. Thoughts against that?

2021-04-14 17:39 UTC, marbemac commented on reference/todos/todo.v1.yaml
> +  - API Key: []
either way technically works - I'd opt in though rather than opt out (because easy to forget to opt out, but nobody will forget to opt in when your operation requires it)

2021-04-14 18:23 UTC, mnaumanali94 commented on reference/todos/todo.v1.yaml
> +  - API Key: []
Done!

2021-04-14 19:39 UTC, marbemac approved these changes

2021-04-14 19:39 UTC, merged